version: '3.1'
services:
  app:
    container_name: bookstore
    image: bookstore
    build: ./
    ports:
      - "8182:8182"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bookstore_db